from __future__ import annotations

CATEGORIES = [
    ("sensor.temperature.digital", "sensor.temperature.digital", "数字温度传感器", "I2C/SMBus 数字温度传感器"),
    ("sensor.hall", "sensor.hall", "霍尔传感器", "低功耗霍尔开关与线性霍尔器件"),
    ("power.ldo", "power.ldo", "LDO", "线性稳压器"),
    ("power.dcdc.buck", "power.dcdc.buck", "Buck 降压", "同步或异步降压型 DC-DC"),
    ("analog.opamp", "analog.opamp", "运算放大器", "通用运放与低功耗运放"),
    ("interface.level_shifter", "interface.level_shifter", "电平转换", "逻辑电平转换器与总线转换器"),
    ("mcu.general", "mcu.general", "MCU", "通用微控制器"),
]

PARAM_DEFINITIONS = [
    ("supply_voltage_min", "供电电压下限", "Supply Voltage Min", "number", "voltage", 1, 1, 1, "*"),
    ("supply_voltage_max", "供电电压上限", "Supply Voltage Max", "number", "voltage", 1, 1, 1, "*"),
    ("input_voltage_min", "输入电压下限", "Input Voltage Min", "number", "voltage", 1, 1, 1, "power.dcdc.buck,power.ldo"),
    ("input_voltage_max", "输入电压上限", "Input Voltage Max", "number", "voltage", 1, 1, 1, "power.dcdc.buck,power.ldo"),
    ("output_voltage_typ", "输出电压", "Output Voltage", "number", "voltage", 1, 1, 1, "power.ldo,power.dcdc.buck"),
    ("output_current_max", "最大输出电流", "Max Output Current", "number", "current", 1, 1, 1, "power.ldo,power.dcdc.buck"),
    ("quiescent_current_typ", "静态电流典型值", "Quiescent Current Typ", "number", "current", 1, 1, 0, "*"),
    ("operating_temp_min", "工作温度下限", "Operating Temp Min", "number", "temperature", 1, 1, 1, "*"),
    ("operating_temp_max", "工作温度上限", "Operating Temp Max", "number", "temperature", 1, 1, 1, "*"),
    ("accuracy_max", "最大精度误差", "Accuracy Max", "number", "accuracy", 1, 1, 1, "sensor.temperature.digital,sensor.hall"),
    ("resolution_bits", "分辨率", "Resolution", "number", "resolution", 1, 1, 0, "sensor.temperature.digital,mcu.general"),
    ("switching_frequency_typ", "开关频率", "Switching Frequency", "number", "frequency", 1, 1, 0, "power.dcdc.buck"),
    ("interface_type", "接口类型", "Interface Type", "text", "interface", 1, 1, 1, "sensor.temperature.digital,interface.level_shifter,mcu.general"),
    ("package", "封装", "Package", "text", "package", 1, 1, 1, "*"),
    ("pin_count", "引脚数", "Pin Count", "number", "count", 1, 1, 0, "*"),
    ("channel_count", "通道数", "Channel Count", "number", "count", 1, 1, 0, "analog.opamp,interface.level_shifter"),
    ("logic_voltage_min", "逻辑电压下限", "Logic Voltage Min", "number", "voltage", 1, 1, 1, "interface.level_shifter"),
    ("logic_voltage_max", "逻辑电压上限", "Logic Voltage Max", "number", "voltage", 1, 1, 1, "interface.level_shifter"),
    ("bandwidth_typ", "带宽", "Bandwidth", "number", "frequency", 1, 1, 0, "analog.opamp"),
    ("slew_rate_typ", "压摆率", "Slew Rate", "number", "slew", 1, 1, 0, "analog.opamp"),
    ("memory_flash_kb", "Flash 容量", "Flash KB", "number", "memory", 1, 1, 0, "mcu.general"),
    ("memory_ram_kb", "RAM 容量", "RAM KB", "number", "memory", 1, 1, 0, "mcu.general"),
]

CATEGORY_TEMPLATES = [
    ("sensor.temperature.digital", "interface_type", 20, 1, 1, "interface_match"),
    ("sensor.temperature.digital", "supply_voltage_min", 14, 1, 1, "range_cover"),
    ("sensor.temperature.digital", "supply_voltage_max", 14, 1, 1, "range_cover"),
    ("sensor.temperature.digital", "operating_temp_min", 14, 1, 1, "range_cover"),
    ("sensor.temperature.digital", "operating_temp_max", 14, 1, 1, "range_cover"),
    ("sensor.temperature.digital", "accuracy_max", 16, 0, 0, "lower_better"),
    ("sensor.temperature.digital", "package", 8, 1, 0, "package_match"),
    ("sensor.hall", "supply_voltage_min", 12, 1, 1, "range_cover"),
    ("sensor.hall", "supply_voltage_max", 12, 1, 1, "range_cover"),
    ("sensor.hall", "operating_temp_min", 14, 1, 1, "range_cover"),
    ("sensor.hall", "operating_temp_max", 14, 1, 1, "range_cover"),
    ("sensor.hall", "quiescent_current_typ", 16, 0, 0, "lower_better"),
    ("sensor.hall", "package", 10, 1, 0, "package_match"),
    ("power.ldo", "input_voltage_min", 12, 1, 1, "range_cover"),
    ("power.ldo", "input_voltage_max", 12, 1, 1, "range_cover"),
    ("power.ldo", "output_voltage_typ", 20, 1, 1, "voltage_close"),
    ("power.ldo", "output_current_max", 18, 1, 1, "higher_better"),
    ("power.ldo", "quiescent_current_typ", 10, 0, 0, "lower_better"),
    ("power.ldo", "output_noise_typ", 10, 0, 0, "lower_better"),
    ("power.ldo", "psrr_typ", 10, 0, 0, "higher_better"),
    ("power.ldo", "operating_temp_min", 6, 0, 0, "range_cover"),
    ("power.ldo", "operating_temp_max", 6, 0, 0, "range_cover"),
    ("power.ldo", "package", 10, 1, 0, "package_match"),
    ("power.dcdc.buck", "input_voltage_min", 12, 1, 1, "range_cover"),
    ("power.dcdc.buck", "input_voltage_max", 12, 1, 1, "range_cover"),
    ("power.dcdc.buck", "output_voltage_typ", 18, 1, 1, "voltage_close"),
    ("power.dcdc.buck", "output_current_max", 18, 1, 1, "higher_better"),
    ("power.dcdc.buck", "switching_frequency_typ", 12, 0, 0, "higher_better"),
    ("power.dcdc.buck", "package", 10, 1, 0, "package_match"),
    ("analog.opamp", "supply_voltage_min", 10, 1, 1, "range_cover"),
    ("analog.opamp", "supply_voltage_max", 10, 1, 1, "range_cover"),
    ("analog.opamp", "bandwidth_typ", 18, 0, 0, "higher_better"),
    ("analog.opamp", "slew_rate_typ", 14, 0, 0, "higher_better"),
    ("analog.opamp", "channel_count", 14, 1, 1, "equals"),
    ("analog.opamp", "package", 10, 1, 0, "package_match"),
    ("interface.level_shifter", "logic_voltage_min", 14, 1, 1, "range_cover"),
    ("interface.level_shifter", "logic_voltage_max", 14, 1, 1, "range_cover"),
    ("interface.level_shifter", "interface_type", 18, 1, 1, "interface_match"),
    ("interface.level_shifter", "channel_count", 16, 1, 0, "higher_better"),
    ("interface.level_shifter", "package", 10, 1, 0, "package_match"),
    ("mcu.general", "supply_voltage_min", 10, 1, 1, "range_cover"),
    ("mcu.general", "supply_voltage_max", 10, 1, 1, "range_cover"),
    ("mcu.general", "memory_flash_kb", 18, 0, 0, "higher_better"),
    ("mcu.general", "memory_ram_kb", 14, 0, 0, "higher_better"),
    ("mcu.general", "interface_type", 12, 0, 0, "contains"),
    ("mcu.general", "package", 10, 1, 0, "package_match"),
]

DOMESTIC_BRANDS = [
    ("brand-sgmicro", "圣邦微", "圣邦微电子", "SGMICRO,SGM", 0.98, "演示国产品牌映射"),
    ("brand-novosense", "纳芯微", "纳芯微电子", "NOVOSENSE,NS", 0.98, "演示国产品牌映射"),
    ("brand-3peak", "思瑞浦", "思瑞浦微电子", "3PEAK,TP", 0.98, "演示国产品牌映射"),
    ("brand-joulwatt", "杰华特", "杰华特微电子", "JOULWATT,JW", 0.98, "演示国产品牌映射"),
    ("brand-chipown", "芯朋微", "芯朋微电子", "CHIPOWN", 0.98, "演示国产品牌映射"),
    ("brand-wch", "沁恒", "沁恒微电子", "WCH,QINHENG", 0.98, "演示国产品牌映射"),
    ("brand-fudan", "复旦微", "复旦微电子", "FUDAN", 0.95, "演示国产品牌映射"),
]

PACKAGE_COMPATIBILITY = [
    ("SOT563-6", "SOT23-6", "partial", "尺寸与焊盘通常需复核"),
    ("SOT23-5", "SOT23-6", "partial", "引脚定义需复核"),
    ("TSSOP-8", "MSOP-8", "partial", "封装不等同，布局需调整"),
    ("X2SON-5", "X2SON-5", "exact", "封装完全一致"),
    ("DFN-6", "DFN-6", "exact", "封装完全一致"),
]

PARTS = [
    {
        "id": "temp-sgm-demo-01",
        "mpn": "DEMO-SGM-TEMP-01",
        "brand": "圣邦微",
        "manufacturer": "圣邦微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "sensor.temperature.digital",
        "subcategory": "digital-temperature-sensor",
        "package": "X2SON-5",
        "package_raw": "X2SON-5",
        "description": "演示型数字温度传感器，I2C/SMBus 兼容",
        "stock_qty": 12800,
        "price_min": 1.85,
        "aliases": ["温度传感器", "SMBus 温度传感器"],
        "params": [
            ("supply_voltage_min", 1.4, 1.4, None, None, "1.4V", "V"),
            ("supply_voltage_max", 3.6, None, None, 3.6, "3.6V", "V"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("accuracy_max", 1.0, None, None, 1.0, "±1.0°C", "°C"),
            ("resolution_bits", 12, None, None, None, "12-bit", "bit"),
            ("interface_type", None, None, None, None, "I2C,SMBus", ""),
            ("package", None, None, None, None, "X2SON-5", ""),
            ("pin_count", 5, None, None, None, "5", "pin"),
        ],
    },
    {
        "id": "temp-ns-demo-02",
        "mpn": "DEMO-NS-TEMP-02",
        "brand": "纳芯微",
        "manufacturer": "纳芯微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "sensor.temperature.digital",
        "subcategory": "digital-temperature-sensor",
        "package": "SOT563-6",
        "package_raw": "SOT563-6",
        "description": "演示型低功耗数字温度传感器",
        "stock_qty": 9200,
        "price_min": 1.62,
        "aliases": ["I2C 温度监测", "低功耗温度传感器"],
        "params": [
            ("supply_voltage_min", 1.7, 1.7, None, None, "1.7V", "V"),
            ("supply_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("accuracy_max", 1.5, None, None, 1.5, "±1.5°C", "°C"),
            ("resolution_bits", 12, None, None, None, "12-bit", "bit"),
            ("interface_type", None, None, None, None, "I2C,SMBus", ""),
            ("package", None, None, None, None, "SOT563-6", ""),
            ("pin_count", 6, None, None, None, "6", "pin"),
        ],
    },
    {
        "id": "hall-sgm-demo-01",
        "mpn": "DEMO-SGM-HALL-01",
        "brand": "圣邦微",
        "manufacturer": "圣邦微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "sensor.hall",
        "subcategory": "hall-switch",
        "package": "SOT23-3",
        "package_raw": "SOT23-3",
        "description": "演示型低功耗霍尔开关",
        "stock_qty": 15000,
        "price_min": 0.68,
        "aliases": ["霍尔开关", "磁传感器"],
        "params": [
            ("supply_voltage_min", 1.65, 1.65, None, None, "1.65V", "V"),
            ("supply_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("quiescent_current_typ", 1.8, None, 1.8, None, "1.8µA", "µA"),
            ("package", None, None, None, None, "SOT23-3", ""),
            ("pin_count", 3, None, None, None, "3", "pin"),
        ],
    },
    {
        "id": "hall-ns-demo-02",
        "mpn": "DEMO-NS-HALL-02",
        "brand": "纳芯微",
        "manufacturer": "纳芯微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "sensor.hall",
        "subcategory": "hall-switch",
        "package": "TO-92-3",
        "package_raw": "TO-92-3",
        "description": "演示型通用霍尔开关传感器",
        "stock_qty": 8800,
        "price_min": 0.55,
        "aliases": ["霍尔", "磁开关"],
        "params": [
            ("supply_voltage_min", 2.5, 2.5, None, None, "2.5V", "V"),
            ("supply_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 150, None, None, 150, "150°C", "°C"),
            ("quiescent_current_typ", 3.2, None, 3.2, None, "3.2µA", "µA"),
            ("package", None, None, None, None, "TO-92-3", ""),
            ("pin_count", 3, None, None, None, "3", "pin"),
        ],
    },
    {
        "id": "ldo-sgmicro-sgm2059-12-sot23",
        "mpn": "SGM2059-1.2XN5G/TR",
        "brand": "圣邦微",
        "manufacturer": "圣邦微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "power.ldo",
        "subcategory": "fixed-ldo",
        "package": "SOT23-5",
        "package_raw": "SOT23-5",
        "description": "300mA 低 VIN、低噪声、高 PSRR、低 IQ 线性稳压器",
        "stock_qty": 9800,
        "price_min": 0.94,
        "aliases": ["SGM2059", "低噪声 LDO", "RF LDO"],
        "params": [
            ("input_voltage_min", 1.1, 1.1, None, None, "1.1V", "V"),
            ("input_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("output_voltage_typ", 1.2, None, 1.2, None, "1.2V", "V"),
            ("output_current_max", 0.3, None, None, 0.3, "300mA", "A"),
            ("quiescent_current_typ", 13, None, 13, None, "13µA", "µA"),
            ("output_noise_typ", 0.0000095, None, 0.0000095, None, "9.5µVRMS", "V"),
            ("psrr_typ", 92, None, 92, None, "92dB", "dB"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "SOT23-5", ""),
            ("pin_count", 5, None, None, None, "5", "pin"),
        ],
    },
    {
        "id": "ldo-3peak-tpl903212-sot23",
        "mpn": "TPL903212-S5TR",
        "brand": "思瑞浦",
        "manufacturer": "思瑞浦微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "power.ldo",
        "subcategory": "fixed-ldo",
        "package": "SOT23-5",
        "package_raw": "SOT23-5",
        "description": "300mA 高 PSRR、超低噪声线性稳压器",
        "stock_qty": 8600,
        "price_min": 1.58,
        "aliases": ["TPL9032", "低噪声 LDO", "高 PSRR LDO"],
        "params": [
            ("input_voltage_min", 1.75, 1.75, None, None, "1.75V", "V"),
            ("input_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("output_voltage_typ", 1.2, None, 1.2, None, "1.2V", "V"),
            ("output_current_max", 0.3, None, None, 0.3, "300mA", "A"),
            ("quiescent_current_typ", 120, None, 120, None, "120µA", "µA"),
            ("output_noise_typ", 0.0000086, None, 0.0000086, None, "8.6µVRMS", "V"),
            ("psrr_typ", 81.9, None, 81.9, None, "81.9dB", "dB"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "SOT23-5", ""),
            ("pin_count", 5, None, None, None, "5", "pin"),
        ],
    },
    {
        "id": "buck-chipown-demo-01",
        "mpn": "DEMO-CO-BUCK-01",
        "brand": "芯朋微",
        "manufacturer": "芯朋微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "power.dcdc.buck",
        "subcategory": "buck-converter",
        "package": "SOT23-6",
        "package_raw": "SOT23-6",
        "description": "演示型 1A 降压转换器",
        "stock_qty": 10300,
        "price_min": 0.76,
        "aliases": ["Buck", "降压 DC-DC"],
        "params": [
            ("input_voltage_min", 4.5, 4.5, None, None, "4.5V", "V"),
            ("input_voltage_max", 24, None, None, 24, "24V", "V"),
            ("output_voltage_typ", 3.3, None, 3.3, None, "3.3V", "V"),
            ("output_current_max", 1.0, None, None, 1.0, "1A", "A"),
            ("switching_frequency_typ", 1200, None, 1200, None, "1.2MHz", "kHz"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "SOT23-6", ""),
            ("pin_count", 6, None, None, None, "6", "pin"),
        ],
    },
    {
        "id": "buck-jw-demo-02",
        "mpn": "DEMO-JW-BUCK-02",
        "brand": "杰华特",
        "manufacturer": "杰华特微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "power.dcdc.buck",
        "subcategory": "buck-converter",
        "package": "SOT23-6",
        "package_raw": "SOT23-6",
        "description": "演示型 2A 同步降压转换器",
        "stock_qty": 8700,
        "price_min": 0.98,
        "aliases": ["同步 Buck", "高电流降压"],
        "params": [
            ("input_voltage_min", 4.0, 4.0, None, None, "4.0V", "V"),
            ("input_voltage_max", 18, None, None, 18, "18V", "V"),
            ("output_voltage_typ", 3.3, None, 3.3, None, "3.3V", "V"),
            ("output_current_max", 2.0, None, None, 2.0, "2A", "A"),
            ("switching_frequency_typ", 1000, None, 1000, None, "1MHz", "kHz"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "SOT23-6", ""),
            ("pin_count", 6, None, None, None, "6", "pin"),
        ],
    },
    {
        "id": "opamp-3peak-demo-01",
        "mpn": "DEMO-3PEAK-OPA-01",
        "brand": "思瑞浦",
        "manufacturer": "思瑞浦微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "analog.opamp",
        "subcategory": "general-opamp",
        "package": "MSOP-8",
        "package_raw": "MSOP-8",
        "description": "演示型轨到轨运算放大器",
        "stock_qty": 7400,
        "price_min": 0.96,
        "aliases": ["运放", "Rail-to-Rail 运放"],
        "params": [
            ("supply_voltage_min", 2.1, 2.1, None, None, "2.1V", "V"),
            ("supply_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("bandwidth_typ", 1000, None, 1000, None, "1MHz", "kHz"),
            ("slew_rate_typ", 0.6, None, 0.6, None, "0.6V/µs", "V/us"),
            ("channel_count", 2, None, None, None, "2", "channel"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "MSOP-8", ""),
            ("pin_count", 8, None, None, None, "8", "pin"),
        ],
    },
    {
        "id": "ls-ns-demo-01",
        "mpn": "DEMO-NS-LS-01",
        "brand": "纳芯微",
        "manufacturer": "纳芯微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "interface.level_shifter",
        "subcategory": "bidirectional-level-shifter",
        "package": "TSSOP-8",
        "package_raw": "TSSOP-8",
        "description": "演示型双向电平转换器",
        "stock_qty": 5400,
        "price_min": 0.82,
        "aliases": ["电平转换", "I2C 电平转换"],
        "params": [
            ("logic_voltage_min", 1.2, 1.2, None, None, "1.2V", "V"),
            ("logic_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("interface_type", None, None, None, None, "GPIO,I2C,SMBus", ""),
            ("channel_count", 2, None, None, None, "2", "channel"),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 125, None, None, 125, "125°C", "°C"),
            ("package", None, None, None, None, "TSSOP-8", ""),
            ("pin_count", 8, None, None, None, "8", "pin"),
        ],
    },
    {
        "id": "mcu-wch-demo-01",
        "mpn": "DEMO-WCH-MCU-01",
        "brand": "沁恒",
        "manufacturer": "沁恒微电子",
        "manufacturer_country": "CN",
        "is_domestic": 1,
        "category_id": "mcu.general",
        "subcategory": "32bit-mcu",
        "package": "QFN-32",
        "package_raw": "QFN-32",
        "description": "演示型 32 位 MCU",
        "stock_qty": 5200,
        "price_min": 2.95,
        "aliases": ["MCU", "微控制器"],
        "params": [
            ("supply_voltage_min", 2.0, 2.0, None, None, "2.0V", "V"),
            ("supply_voltage_max", 5.5, None, None, 5.5, "5.5V", "V"),
            ("memory_flash_kb", 64, None, None, 64, "64KB", "KB"),
            ("memory_ram_kb", 20, None, None, 20, "20KB", "KB"),
            ("interface_type", None, None, None, None, "I2C,SPI,UART,USB", ""),
            ("operating_temp_min", -40, -40, None, None, "-40°C", "°C"),
            ("operating_temp_max", 85, None, None, 85, "85°C", "°C"),
            ("package", None, None, None, None, "QFN-32", ""),
            ("pin_count", 32, None, None, None, "32", "pin"),
        ],
    },
]
